feat: add env flag for rivet cli
rivet-gg/opengb pull request #243
Opened 2024-03-13 23:57 UTC by MasterPtato

2024-04-17 20:55 UTC, NathanFlurry approved these changes

2024-04-17 20:56 UTC, NathanFlurry requested changes

2024-04-17 20:56 UTC, NathanFlurry commented on src/cli/commands/db.ts
> +	.globalOption("--env <environment:string>", "Managed OpenGB environment used by the Rivet CLI")
Can we only show this if we detect this is running form the Rivet CLI? Should be pretty easy to pass an env var saying this is a Rivet subcommand.

2024-04-24 04:14 UTC, NathanFlurry approved these changes

2024-04-24 16:58 UTC, MasterPtato commented
### Merge activity

* **Apr 24, 12:58 PM EDT**: @MasterPtato started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/rivet-gg/opengb/243).

2024-04-24 17:02 UTC, merged