feat: add durable storage MVP
rivet-gg/opengb pull request #267
Opened 2024-05-10 23:48 UTC by MasterPtato

2024-05-10 23:48 UTC, MasterPtato commented
* **#267** <a href="https://app.graphite.dev/github/pr/rivet-gg/opengb/267?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MasterPtato and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-05-15 14:04 UTC, Blckbrry-Pi requested changes
Looks great overall!

I don't know too much about durable storage and the idea behind it, but I think the Deno implementation is pretty severely lacking without persistence.

Additionally, most of the comments I left on the Deno impl also apply to the CF impl. 

Again, I apologize for advocating for more typescript complexity, but if instantiating a `Durable` it isn't disallowed by the type system, we NEED to explicitly document that. Module authors will definitely do that by accident.

Additionally, I'm not completely sure what the "point" of the durable storage is. Is that not what postgres and prisma are for?

2024-05-15 14:04 UTC, Blckbrry-Pi commented on src/runtime/durable.ts
> +	constructor(public id: string) {
If you don't want module authors to call the constructor by accident, make sure to make this a `private constructor`.

2024-05-15 18:44 UTC, NathanFlurry commented on tests/basic/modules/foo/scripts/call_self.ts
+1 should be a separate module for testing core functionality e2e

2024-05-15 18:44 UTC, NathanFlurry commented
@MasterPtato would you rather me wait until the next iteration is ready to go or review this now?

2024-05-16 16:58 UTC, MasterPtato commented
@Blckbrry-Pi @NathanFlurry this was meant to be a draft sorry

2024-05-16 22:10 UTC, MasterPtato commented on src/runtime/context.ts
> +				// throw error;
This didnt print the error message in the HTTP response so i returned the actual error instead. I just used it for debugging cf workers

2024-05-16 22:16 UTC, MasterPtato commented on src/runtime/durable.ts
> +	static async for<T extends typeof Durable>(this: T, name: string): Promise<InstanceType<T>> {
This looks like too much black magic for a non-issue like this

2024-05-16 22:17 UTC, MasterPtato commented on src/runtime/durable.ts
> +// In-memory storage implementation
This is for the MVP and only used with `opengb dev`, the managed opengb version with cloudflare is persistent. We can add written file persistence later if needed

2024-05-25 03:41 UTC, NathanFlurry commented
@MasterPtato merging this since it's blocking other things. let's make sure this gets cleaned up at some point soon.

2024-05-25 03:41 UTC, NathanFlurry commented
### Merge activity

* **May 24, 11:41 PM EDT**: @NathanFlurry started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/rivet-gg/opengb/267).

2024-05-25 03:43 UTC, merged