Added confirmation for `opengb init` command
rivet-gg/opengb pull request #279
Opened 2024-05-18 08:26 UTC by vr-varad

**Implementation**

Say which files were created
Link to docs on getting started

**solution Implementation**

The `templateProject` function now returns a Promise of type `string[]`, tracking the paths of created files and directories and resolving with this array. Error handling is implemented to catch and log errors, returning an empty array if creation fails.

2024-05-18 08:29 UTC, vr-varad commented
Hey @NathanFlurry  I have implemented the solution as discussed. I would appreciate it if you could review it at your earliest convenience. Please let me know if you have any questions or require further clarification. Thank you.

2024-05-18 20:17 UTC, NathanFlurry requested changes
welcome, thanks for the pr!

using this in practice, i don't think it actually makes sense to print the files. would simplify intro to something like:

```
Project created successfully

Created config file at backend.yaml

Get started at https://opengb.dev/introduction
```

2024-05-18 20:17 UTC, NathanFlurry commented on src/cli/commands/init.ts
>  export const initCommand = new Command<GlobalOpts>()
this file has inconsistent indentation, should be using hard tabs

2024-05-19 04:58 UTC, vr-varad commented
@NathanFlurry I have made the required changes.

2024-05-25 03:48 UTC, NathanFlurry approved these changes

2024-05-25 03:48 UTC, merged

2024-05-25 03:49 UTC, NathanFlurry commented
@vr-varad thanks for the pr! apologies for the ticket being wrong, i pushed some small tweaks.